Repository Alfresco/alfresco-process-infrastructure-deployment, pull requests merged in 2020-05, with the labels that each got.

#22 Updating model and admin app ingress path value
  helm/alfresco-process-infrastructure/requirements.yaml
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: partially-approved

#24 Update admin and model image tag
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved

#26 Reverting admin and model ingress path value
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved

#27 AAE-2543 set release version to 7.1.0-M7
  Makefile
  README.md
  helm/alfresco-process-infrastructure/Chart.yaml
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/requirements.yaml
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: unreviewed

#28 [AAE-1964] - Upgrade to Identity Service 1.2 (Keycloak 8.0.1)
  helm/alfresco-process-infrastructure/requirements.yaml
Labels: PR: partially-approved

#29 AAE-2646 update image tag to develop after release so automation can …
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved

#30 AAE-2646 update version to 7.1.0-M8
  helm/alfresco-process-infrastructure/Chart.yaml
  helm/alfresco-process-infrastructure/README.md
Labels: PR: unreviewed

#31 AAE-2734 updated README and removed unused scripts
  README.md
  install-ingress.sh
  install-registry.sh
Labels: PR: unreviewed

#32 [AAE-2605] - upgrade apiVersion and postgres chart to support Kubernetes version 1.16
  helm/alfresco-process-infrastructure/requirements.yaml
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: unreviewed

#33 AAE-2753 upgrade to helm 3
  README.md
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/requirements.yaml
  install.sh
  values-docker-desktop.yaml
Labels: PR: unreviewed
