Repository Alfresco/alfresco-process-infrastructure-deployment, pull requests merged in 2020-04, with the labels that each got.

#16 AAE-2342 Remove internal port value since it is a default
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved

#17 AAE-2420 rename volume variables and add default values
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved

#18 [AAE-2422] - update image from M6 to develop branch
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: partially-approved

#19 [AAE-2422] - update image from M6 to develop branch
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved

#15 [ACS-26] - remove ACS deployment from AAE chart
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/requirements.yaml
  helm/alfresco-process-infrastructure/templates/NOTES.txt
  helm/alfresco-process-infrastructure/templates/setup-acs-script-job.yaml
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: partially-approved

#20 AAE-2388 removed dmn and script because now they are merged in Modeling
  helm/alfresco-process-infrastructure/requirements.yaml
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved

#21 Fix ingress for modeling service
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved

#23 AAE-2524 use develop tag for all images in development
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: unreviewed
