Repository Alfresco/alfresco-process-infrastructure-deployment, pull requests merged in 2020-07, with the labels that each got.

#45 [AAE-2993]- update chart version 7.1.0-M8 to 7.1.0-M9
  helm/alfresco-process-infrastructure/Chart.yaml
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: partially-approved

#41 AAE-2951 upgrade identity chart to 2.1.0
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/requirements.yaml
Labels: PR: unreviewed

#47 AAE-3038 allow external ACS and credentials
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/templates/_helpers.tpl
  helm/alfresco-process-infrastructure/templates/setup-acs-script-job.yaml
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved

#49 [AAE-3094]- Update helm charts to provide APP_CONFIG_ECM_HOST to admin app
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved

#50 Update alfresco-adf-app to 2.2.2 for AAE-3151
  helm/alfresco-process-infrastructure/requirements.yaml
Labels: PR: partially-approved

#51 [AAE-3172] - update ecm host url conditional based on the acs
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved
