Repository Alfresco/alfresco-process-infrastructure-deployment, pull requests merged in 2020-09, with the labels that each got.

#53 [AAE-3329] - update adf & spring-boot chart to latest on incubator
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/requirements.yaml
Labels: PR: reviewed-approved

#54 [AAE-3345] - remove docker-registry configuration from deployment-service
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/templates/aps2-registry-secret.yaml
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved

#55 AAE-3097 extract value for apps default image tag
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: partially-approved

#56 Update according to charts on incubator from A1 to M10
  helm/alfresco-process-infrastructure/requirements.yaml
Labels: PR: reviewed-approved

#57 [AAE-3595] - add process storage service secret variable
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: unreviewed

#59 [AAE-3596] - add activiti keycloak clinet password variable
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: unreviewed

#60 AAE-3571 remove files commited by mistake
  helm/alfresco-process-infrastructure/update-version.sh
  helm/alfresco-process-infrastructure/values.yaml-e
  helm/alfresco-process-infrastructure/values.yaml.bak
Labels: PR: unreviewed
