Repository Alfresco/alfresco-process-infrastructure-deployment, pull requests merged in 2021-09, with the labels that each got.

#114 AAE-5586 make password strong and random
  helm/alfresco-process-infrastructure/functions_acs.sh
  helm/alfresco-process-infrastructure/setup_acs.sh
Labels: PR: partially-approved

#116 Fix the add user to group script
  helm/alfresco-process-infrastructure/functions_acs.sh
Labels: PR: reviewed-approved

#115 fix(AAE-3773): Use client/secret auth for Keycloak Admin Client
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: unreviewed

#117 AAE-5817 Add PROCESS_UI_URL to deployment service environment
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved

#118 AAE-5572 Bump up Tika version to 2.5.3
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved

#119 updated password generator for functions acs script
  helm/alfresco-process-infrastructure/functions_acs.sh
Labels: PR: partially-approved

#122 AAE-5911 bump up identity service to 1.6.0
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/requirements.yaml
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: unreviewed
