Repository Alfresco/alfresco-process-infrastructure-deployment, pull requests merged in 2022-07, with the labels that each got.

#147 Update docker image tags to version 7.5.0-alpha.1
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: unreviewed, updatebot

#165 AAE-9367 enable auto-merge for propagation PRs
  .github/workflows/versions-propagation-auto-merge.yml
Labels: PR: partially-approved

#167 Update docker image tags to version 7.5.0-alpha.7
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#160 Update docker image tags to version 7.5.0-alpha.3
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#168 Update docker image tags to version 7.5.0-alpha.4
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#169 Update docker image tags to version 7.5.0-alpha.11
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#172 Update docker image tags to version 7.5.0-alpha.9
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#176 Update docker image tags to version 7.5.0-alpha.11
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#178 AAE-9367 trigger auto-merge workflow also on PR labeled
  .github/workflows/versions-propagation-auto-merge.yml
Labels: PR: partially-approved

#179 Update deployment-service docker image tag to 7.5.0-alpha.15
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#180 Update modeling-service docker image tag to 7.5.0-alpha.12
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#181 Update process-analytics docker image tags to 7.5.0-alpha.6
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#183 AAE-9367 trigger the automerge-workflow only when a label is added
  .github/workflows/versions-propagation-auto-merge.yml
Labels: PR: partially-approved

#189 Update deployment-service docker image tag to 7.5.0-alpha.19
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#190 Update modeling-service docker image tag to 7.5.0-alpha.13
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#191 Update modeling-service docker image tag to 7.5.0-alpha.14
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#192 Update deployment-service docker image tag to 7.5.0-alpha.20
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#187 AAE-9036 add new identity adapter service
  helm/alfresco-process-infrastructure/Chart.yaml
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: unreviewed

#193 Update process-analytics docker image tags to 7.5.0-alpha.9
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#194 Update deployment-service docker image tag to 7.5.0-alpha.21
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#199 Update process-analytics docker image tags to 7.5.0-alpha.13
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#200 Update deployment-service docker image tag to 7.5.0-alpha.23
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#201 Update modeling-service docker image tag to 7.5.0-alpha.15
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#202 Update deployment-service docker image tag to 7.5.0-alpha.24
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#203 Update deployment-service docker image tag to 7.5.0-alpha.25
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#205 Update deployment-service docker image tag to 7.5.0-alpha.26
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#206 Update deployment-service docker image tag to 7.5.0-alpha.27
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#208 Update deployment-service docker image tag to 7.5.0-alpha.28
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#209 Update modeling-service docker image tag to 7.5.0-alpha.16
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#210 Update deployment-service docker image tag to 7.5.0-alpha.29
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#211 Update modeling-service docker image tag to 7.5.0-alpha.17
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#212 Update process-analytics docker image tags to 7.5.0-alpha.16
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#214 Update modeling-service docker image tag to 7.5.0-alpha.18
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#215 Update deployment-service docker image tag to 7.5.0-alpha.31
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#216 Update deployment-service docker image tag to 7.5.0-alpha.32
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#218 Update deployment-service docker image tag to 7.5.0-alpha.33
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#219 Update process-analytics docker image tags to 7.5.0-alpha.17
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#222 Update deployment-service docker image tag to 7.5.0-alpha.35
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#223 Update modeling-service docker image tag to 7.5.0-alpha.21
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#224 Update process-analytics docker image tags to 7.5.0-alpha.18
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#225 Update deployment-service docker image tag to 7.5.0-alpha.36
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#226 Update modeling-service docker image tag to 7.5.0-alpha.22
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#227 Update process-analytics docker image tags to 7.5.0-alpha.19
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#228 Update deployment-service docker image tag to 7.5.0-alpha.37
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#229 Update modeling-service docker image tag to 7.5.0-alpha.23
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#231 Update identity-adapter-service docker image tag to 7.5.0-alpha.4
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#232 Update identity-adapter-service docker image tag to 7.5.0-alpha.5
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#234 Update deployment-service docker image tag to 7.5.0-alpha.39
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#235 Update deployment-service docker image tag to 7.5.0-alpha.40
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#237 Update modeling-service docker image tag to 7.5.0-alpha.24
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#239 Update process-analytics docker image tags to 7.5.0-alpha.21
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#240 Update deployment-service docker image tag to 7.5.0-alpha.42
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#242 Update deployment-service docker image tag to 7.5.0-alpha.43
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#243 Update deployment-service docker image tag to 7.5.0-alpha.44
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#244 Update deployment-service docker image tag to 7.5.0-alpha.45
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#245 Update process-analytics docker image tags to 7.5.0-alpha.22
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#246 Update modeling-service docker image tag to 7.5.0-alpha.26
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#248 Update process-analytics docker image tags to 7.5.0-alpha.23
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#251 Update process-analytics docker image tags to 7.5.0-alpha.24
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#252 Update deployment-service docker image tag to 7.5.0-alpha.48
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#255 Update deployment-service docker image tag to 7.5.0-alpha.49
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#256 Update modeling-service docker image tag to 7.5.0-alpha.29
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#257 Update modeling-service docker image tag to 7.5.0-alpha.30
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#258 Update deployment-service docker image tag to 7.5.0-alpha.50
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#259 Update process-analytics docker image tags to 7.5.0-alpha.26
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#260 Update modeling-service docker image tag to 7.5.0-alpha.31
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#262 Update modeling-service docker image tag to 7.5.0-alpha.32
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#263 Update modeling-service docker image tag to 7.5.0-alpha.33
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#264 Update process-analytics docker image tags to 7.5.0-alpha.27
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#265 Update deployment-service docker image tag to 7.5.0-alpha.52
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#266 Update deployment-service docker image tag to 7.5.0-alpha.53
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#267 Update modeling-service docker image tag to 7.5.0-alpha.34
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#269 Update process-analytics docker image tags to 7.5.0-alpha.28
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#270 Update modeling-service docker image tag to 7.5.0-alpha.35
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#272 Update identity-adapter-service docker image tag to 7.5.0-alpha.7
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#273 Update process-analytics docker image tags to 7.5.0-alpha.29
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#276 Update identity-adapter-service docker image tag to 7.5.0-alpha.8
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#277 Update modeling-service docker image tag to 7.5.0-alpha.37
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#278 Update deployment-service docker image tag to 7.5.0-alpha.56
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#279 Update process-analytics docker image tags to 7.5.0-alpha.30
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#281 Update modeling-service docker image tag to 7.5.0-alpha.38
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#282 Update deployment-service docker image tag to 7.5.0-alpha.58
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#283 Update deployment-service docker image tag to 7.5.0-alpha.59
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#284 Update process-analytics docker image tags to 7.5.0-alpha.31
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#285 Update modeling-service docker image tag to 7.5.0-alpha.39
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#287 Update process-analytics docker image tags to 7.5.0-alpha.32
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#288 Update deployment-service docker image tag to 7.5.0-alpha.61
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#289 Update modeling-service docker image tag to 7.5.0-alpha.40
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: unreviewed

#290 Update deployment-service docker image tag to 7.5.0-alpha.62
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#291 Update deployment-service docker image tag to 7.5.0-alpha.63
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#292 Update modeling-service docker image tag to 7.5.0-alpha.41
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#293 Update process-analytics docker image tags to 7.5.0-alpha.33
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#294 Update identity-adapter-service docker image tag to 7.5.0-alpha.9
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#295 Update deployment-service docker image tag to 7.5.0-alpha.64
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#296 Update process-analytics docker image tags to 7.5.0-alpha.34
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#297 Update deployment-service docker image tag to 7.5.0-alpha.65
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#298 Update modeling-service docker image tag to 7.5.0-alpha.42
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#299 Update process-analytics docker image tags to 7.5.0-alpha.35
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#300 Update modeling-service docker image tag to 7.5.0-alpha.43
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#301 Update deployment-service docker image tag to 7.5.0-alpha.66
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#302 Update deployment-service docker image tag to 7.5.0-alpha.67
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#303 Update identity-adapter-service docker image tag to 7.5.0-alpha.10
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#304 Update deployment-service docker image tag to 7.5.0-alpha.68
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#305 Update modeling-service docker image tag to 7.5.0-alpha.44
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#306 Update identity-adapter-service docker image tag to 7.5.0-alpha.11
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#307 Update deployment-service docker image tag to 7.5.0-alpha.69
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#308 Update process-analytics docker image tags to 7.5.0-alpha.36
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#309 Update modeling-service docker image tag to 7.5.0-alpha.45
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#310 Update identity-adapter-service docker image tag to 7.5.0-alpha.12
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#311 Update deployment-service docker image tag to 7.5.0-alpha.70
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#312 Update identity-adapter-service docker image tag to 7.5.0-alpha.13
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#313 Update deployment-service docker image tag to 7.5.0-alpha.71
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#314 Update modeling-service docker image tag to 7.5.0-alpha.46
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#315 Update deployment-service docker image tag to 7.5.0-alpha.72
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#316 Update process-analytics docker image tags to 7.5.0-alpha.37
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#317 Update identity-adapter-service docker image tag to 7.5.0-alpha.14
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#318 Update identity-adapter-service docker image tag to 7.5.0-alpha.15
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#319 Update modeling-service docker image tag to 7.5.0-alpha.47
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#320 Update deployment-service docker image tag to 7.5.0-alpha.73
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#321 Update process-analytics docker image tags to 7.5.0-alpha.38
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#322 Update identity-adapter-service docker image tag to 7.5.0-alpha.16
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#323 Update modeling-service docker image tag to 7.5.0-alpha.48
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#324 Update deployment-service docker image tag to 7.5.0-alpha.74
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#325 Update deployment-service docker image tag to 7.5.0-alpha.75
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot
