Repository Alfresco/alfresco-process-infrastructure-deployment, pull requests merged in 2022-11, with the labels that each got.

#712 Update identity-adapter-service docker image tag to 7.7.0-alpha.2
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#713 Update modeling-service docker image tag to 7.7.0-alpha.3
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#714 Update deployment-service docker image tag to 7.7.0-alpha.5
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#715 Update process-analytics docker image tags to 7.7.0-alpha.3
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#716 Update identity-adapter-service docker image tag to 7.7.0-alpha.3
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#718 Update deployment-service docker image tag to 7.7.0-alpha.6
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#722 Update deployment-service docker image tag to 7.7.0-alpha.8
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#724 Update identity-adapter-service docker image tag to 7.7.0-alpha.5
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#725 Update modeling-service docker image tag to 7.7.0-alpha.6
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#727 Update deployment-service docker image tag to 7.7.0-alpha.10
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#728 Update process-analytics docker image tags to 7.7.0-alpha.6
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#729 Update identity-adapter-service docker image tag to 7.7.0-alpha.6
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#730 Update modeling-service docker image tag to 7.7.0-alpha.7
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#731 Update deployment-service docker image tag to 7.7.0-alpha.11
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#732 Update deployment-service docker image tag to 7.7.0-alpha.12
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#326 AAE-8265: migrate from Travis to GH actions
  .github/dependabot.yml
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/main.yml
  .github/workflows/versions-propagation-auto-merge.yml
  .pre-commit-config.yaml
  .travis.yml
  README.md
  helm/alfresco-process-infrastructure/Chart.yaml
  helm/alfresco-process-infrastructure/README.md
Labels: PR: unreviewed

#739 AAE-8265: use better commit message for helm publish
  .github/workflows/main.yml
Labels: PR: unreviewed

#738 Update deployment-service docker image tag to 7.7.0-alpha.14
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: updatebot

#740 Update deployment-service docker image tag to 7.7.0-alpha.15
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#741 Update deployment-service docker image tag to 7.7.0-alpha.16
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#742 AAE-10136: use helm package path instead of downloading it again
  .github/workflows/main.yml
Labels: PR: unreviewed

#743 Update identity-adapter-service docker image tag to 7.7.0-alpha.7
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#744 Update deployment-service docker image tag to 7.7.0-alpha.17
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#747 Update process-analytics docker image tags to 7.7.0-alpha.7
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#748 Update identity-adapter-service docker image tag to 7.7.0-alpha.8
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#749 Update modeling-service docker image tag to 7.7.0-alpha.9
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#750 Update modeling-service docker image tag to 7.7.0-alpha.10
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#751 Update deployment-service docker image tag to 7.7.0-alpha.18
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#752 Update deployment-service docker image tag to 7.7.0-alpha.19
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#753 Update deployment-service docker image tag to 7.7.0-alpha.20
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#754 Update deployment-service docker image tag to 7.7.0-alpha.21
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#756 Update process-analytics docker image tags to 7.7.0-alpha.8
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#757 Update identity-adapter-service docker image tag to 7.7.0-alpha.9
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#758 Update deployment-service docker image tag to 7.7.0-alpha.22
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#759 Update modeling-service docker image tag to 7.7.0-alpha.11
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#755 AAE-11328: used fixed version for gh action bridgecrewio/checkov-action
  .github/dependabot.yml
  .github/workflows/main.yml
Labels: PR: reviewed-approved

#761 Update process-analytics docker image tags to 7.7.0-alpha.9
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#762 Update identity-adapter-service docker image tag to 7.7.0-alpha.11
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#763 Update modeling-service docker image tag to 7.7.0-alpha.12
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#765 Update deployment-service docker image tag to 7.7.0-alpha.23
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#766 Update deployment-service docker image tag to 7.7.0-alpha.24
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#767 Update deployment-service docker image tag to 7.7.0-alpha.25
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#769 Update modeling-service docker image tag to 7.7.0-alpha.13
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#770 Update deployment-service docker image tag to 7.7.0-alpha.27
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#771 Update deployment-service docker image tag to 7.7.0-alpha.28
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#772 Update process-analytics docker image tags to 7.7.0-alpha.10
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#773 Update modeling-service docker image tag to 7.7.0-alpha.14
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#774 Update deployment-service docker image tag to 7.7.0-alpha.29
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#775 Update process-analytics docker image tags to 7.7.0-alpha.11
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#776 Update modeling-service docker image tag to 7.7.0-alpha.15
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#777 Update deployment-service docker image tag to 7.7.0-alpha.30
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#778 Update identity-adapter-service docker image tag to 7.7.0-alpha.12
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#780 Update identity-adapter-service docker image tag to 7.7.0-alpha.13
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#781 Update modeling-service docker image tag to 7.7.0-alpha.16
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#779 Update process-analytics docker image tags to 7.7.0-alpha.12
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#782 Update deployment-service docker image tag to 7.7.0-alpha.31
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#783 Update deployment-service docker image tag to 7.7.0-alpha.32
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#784 Update process-analytics docker image tags to 7.7.0-alpha.13
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#785 Update process-analytics docker image tags to 7.7.0-alpha.14
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#786 Update identity-adapter-service docker image tag to 7.7.0-alpha.14
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#787 Update modeling-service docker image tag to 7.7.0-alpha.17
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#788 Update deployment-service docker image tag to 7.7.0-alpha.33
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#789 Update deployment-service docker image tag to 7.7.0-alpha.34
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#790 Update process-analytics docker image tags to 7.7.0-alpha.15
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#792 Update modeling-service docker image tag to 7.7.0-alpha.18
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#793 Update deployment-service docker image tag to 7.7.0-alpha.35
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#794 Update process-analytics docker image tags to 7.7.0-alpha.16
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#795 Update identity-adapter-service docker image tag to 7.7.0-alpha.16
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#796 Update modeling-service docker image tag to 7.7.0-alpha.19
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#797 Update process-analytics docker image tags to 7.7.0-alpha.17
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#798 Update identity-adapter-service docker image tag to 7.7.0-alpha.17
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: unreviewed, updatebot

#799 Update modeling-service docker image tag to 7.7.0-alpha.20
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#801 Update process-analytics docker image tags to 7.7.0-alpha.18
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#802 Update identity-adapter-service docker image tag to 7.7.0-alpha.18
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#803 Update modeling-service docker image tag to 7.7.0-alpha.21
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#804 Update deployment-service docker image tag to 7.7.0-alpha.37
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#806 Update process-analytics docker image tags to 7.7.0-alpha.19
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#808 Update modeling-service docker image tag to 7.7.0-alpha.22
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#809 Update deployment-service docker image tag to 7.7.0-alpha.38
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#810 Update process-analytics docker image tags to 7.7.0-alpha.20
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#812 Update modeling-service docker image tag to 7.7.0-alpha.23
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#813 Update deployment-service docker image tag to 7.7.0-alpha.39
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#821 Update process-analytics docker image tags to 7.6.1-alpha.1
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#822 Update identity-adapter-service docker image tag to 7.6.1-alpha.2
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#823 Update modeling-service docker image tag to 7.6.1-alpha.2
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#824 Update deployment-service docker image tag to 7.6.1-alpha.3
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#826 Update process-analytics docker image tags to 7.6.1-alpha.2
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#827 Update identity-adapter-service docker image tag to 7.6.1-alpha.3
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#829 Update deployment-service docker image tag to 7.7.0-alpha.40
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#831 Update process-analytics docker image tags to 7.6.1-alpha.3
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#832 Update modeling-service docker image tag to 7.6.1-alpha.4
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#833 Update identity-adapter-service docker image tag to 7.6.1-alpha.4
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#834 Update deployment-service docker image tag to 7.6.1-alpha.5
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#835 Update process-analytics docker image tags to 7.7.0-alpha.21
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#838 Update deployment-service docker image tag to 7.7.0-alpha.41
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#836 Update identity-adapter-service docker image tag to 7.7.0-alpha.21
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#837 Update modeling-service docker image tag to 7.7.0-alpha.24
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: unreviewed, updatebot

#839 Update process-analytics docker image tags to 7.7.0-alpha.22
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#842 Update deployment-service docker image tag to 7.7.0-alpha.42
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#843 Update deployment-service docker image tag to 7.7.0-alpha.43
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#845 Update deployment-service docker image tag to 7.7.0-alpha.44
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#847 Update process-analytics docker image tags to 7.7.0-alpha.23
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#848 Update identity-adapter-service docker image tag to 7.7.0-alpha.23
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#849 Update modeling-service docker image tag to 7.7.0-alpha.26
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#850 Update deployment-service docker image tag to 7.7.0-alpha.45
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#851 Update deployment-service docker image tag to 7.7.0-alpha.46
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#852 Update process-analytics docker image tags to 7.7.0-alpha.24
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#853 Update identity-adapter-service docker image tag to 7.7.0-alpha.24
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#854 Update modeling-service docker image tag to 7.7.0-alpha.27
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot

#856 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.7.0-alpha.50
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot, develop

#857 chore(deps): upgrade Alfresco/alfresco-process to version 7.7.0-alpha.26
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot, develop

#858 chore(deps): upgrade Alfresco/alfresco-identity-adapter-service to version 7.7.0-alpha.27
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot, develop

#859 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.7.0-alpha.30
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot, develop

#860 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.7.0-alpha.51
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot, develop

#861 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.7.0-alpha.52
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved, updatebot, develop

#825 fix(AAE-11371): Create alpha releases for alfresco-process-infrastructure-deployment
  .github/workflows/main.yml
  .jx/updatebot.yaml
  .m2/settings.xml
  pom.xml
Labels: PR: unreviewed

#864 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.7.0-alpha.53
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#865 chore(deps): upgrade Alfresco/alfresco-process to version 7.7.0-alpha.27
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#866 chore(deps): upgrade Alfresco/alfresco-identity-adapter-service to version 7.7.0-alpha.28
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#867 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.7.0-alpha.31
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#868 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.7.0-alpha.32
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#869 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.7.0-alpha.54
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#870 chore(deps): upgrade Alfresco/alfresco-identity-adapter-service to version 7.7.0-alpha.29
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#871 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.7.0-alpha.55
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#863 chore(deps): upgrade Activiti/activiti-cloud-common-chart to version 7.7.0-alpha.12
  helm/alfresco-process-infrastructure/Chart.yaml
  helm/alfresco-process-infrastructure/README.md
Labels: PR: unreviewed, updatebot, master

#872 chore(deps): upgrade Activiti/activiti-cloud-common-chart to version 7.7.0-alpha.13
  helm/alfresco-process-infrastructure/Chart.yaml
  helm/alfresco-process-infrastructure/README.md
Labels: PR: reviewed-approved, updatebot, master

#873 chore(deps): upgrade Activiti/activiti-cloud-common-chart to version 7.7.0-alpha.14
  helm/alfresco-process-infrastructure/Chart.yaml
  helm/alfresco-process-infrastructure/README.md
Labels: PR: reviewed-approved, updatebot, master

#874 chore(deps): upgrade Activiti/activiti-cloud-common-chart to version 7.7.0-alpha.15
  helm/alfresco-process-infrastructure/Chart.yaml
  helm/alfresco-process-infrastructure/README.md
Labels: PR: reviewed-approved, updatebot, master

#875 chore(deps): upgrade Alfresco/alfresco-process to version 7.7.0-alpha.28
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#876 chore(deps): upgrade Alfresco/alfresco-identity-adapter-service to version 7.7.0-alpha.30
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#878 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.7.0-alpha.58
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#862 fix(AAE-11533): Trigger Github prerelease for Helm charts on release candidate tag
  .github/workflows/rc.yml
  helm/alfresco-process-infrastructure/Chart.yaml
  helm/alfresco-process-infrastructure/README.md
Labels: PR: unreviewed

#879 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.7.0-alpha.59
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#880 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.7.0-alpha.60
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop
