Repository Alfresco/alfresco-process-infrastructure-deployment, pull requests merged in 2022-12, with the labels that each got.

#881 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.7.0-alpha.61
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#882 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.7.0-alpha.63
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#883 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.7.0-alpha.64
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#884 chore(deps): upgrade Activiti/activiti-cloud-common-chart to version 7.7.0-alpha.17
  helm/alfresco-process-infrastructure/Chart.yaml
  helm/alfresco-process-infrastructure/README.md
Labels: PR: reviewed-approved, updatebot, develop

#885 chore(deps): upgrade Activiti/activiti-cloud-common-chart to version 7.7.0-alpha.18
  helm/alfresco-process-infrastructure/Chart.yaml
  helm/alfresco-process-infrastructure/README.md
Labels: PR: reviewed-approved, updatebot, develop

#886 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.7.0-alpha.65
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#887 fix(AAE-11241): use hxp-admin-app image as default
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: partially-approved

#888 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.7.0-alpha.66
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#889 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.7.0-alpha.67
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#890 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.7.0-alpha.68
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#894 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.7.0-alpha.69
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#895 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.7.0-alpha.70
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#897 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.7.0-alpha.72
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#898 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.7.0-alpha.73
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#900 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.7.0-alpha.74
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#901 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.7.0-alpha.76
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#844 [AAE-11409] Add variables to the Deployment Service to properly deploy HxP Process Storage
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: unreviewed

#902 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.7.0-alpha.77
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#903 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.7.0-alpha.78
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#904 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.7.0-alpha.79
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#905 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.7.0-alpha.51
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#906 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.7.0-alpha.80
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#907 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.7.0-alpha.52
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#908 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.7.0-alpha.81
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#909 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.2
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#911 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.3
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#912 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.4
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#913 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.5
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#914 fix(values): update applications image tag to develop
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: partially-approved

#915 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.6
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#916 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.7
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#917 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.8
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#919 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.11
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#920 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.12
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#921 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.14
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#922 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.15
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#925 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.16
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#926 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.17
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#927 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.18
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#928 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.8.0-alpha.9
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#929 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.19
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#932 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.20
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#931 AAE-11895 Add Github release.yml changelog template
  .github/release.yml
Labels: PR: partially-approved

#930 AAE-11894 Remove create prerelease step for rc tag workflow
  .github/workflows/rc.yml
Labels: enhancement, PR: unreviewed, PR: partially-approved

#933 chore(deps): upgrade Alfresco/alfresco-identity-adapter-service to version 7.8.0-alpha.10
  helm/alfresco-process-infrastructure/Chart.yaml
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#934 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.21
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#935 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.22
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#936 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.23
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#937 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.24
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#938 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.25
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#939 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.26
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#940 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.27
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop
