Repository Alfresco/alfresco-process-infrastructure-deployment, pull requests merged in 2023-04, with the labels that each got.

#1095 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.54
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1097 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.56
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1098 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.10.0-alpha.39
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1099 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.57
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1100 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.61
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1101 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.10.0-alpha.43
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1102 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.62
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1103 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.63
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1104 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.64
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1105 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.10.0-alpha.46
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1106 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.65
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1107 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.66
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1108 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.67
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1109 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.68
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1110 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.69
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1111 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.70
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1112 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.71
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1113 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.73
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1114 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.10.0-alpha.52
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1115 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.74
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1116 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.75
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1119 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.79
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1120 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.80
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1121 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.81
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1123 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.85
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1124 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.86
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1125 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.88
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1126 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.89
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1127 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.90
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1129 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.92
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1130 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.93
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1131 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.94
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1132 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.95
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1133 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.96
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1136 chore(deps): upgrade Activiti/activiti-cloud-common-chart to version 7.10.0-alpha.2
  helm/alfresco-process-infrastructure/Chart.yaml
  helm/alfresco-process-infrastructure/README.md
Labels: PR: reviewed-approved, updatebot, develop

#1137 chore(deps): upgrade Alfresco/alfresco-identity-adapter-service to version 7.10.0-alpha.48
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1138 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.98
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1139 [AAE-14008] Add HXP_CONTEXT_ENVIRONMENT
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: partially-approved

#1140 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.99
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1141 chore(deps): upgrade Activiti/activiti-cloud-common-chart to version 7.10.0-alpha.3
  helm/alfresco-process-infrastructure/Chart.yaml
  helm/alfresco-process-infrastructure/README.md
Labels: PR: reviewed-approved, updatebot, develop

#1142 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.100
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1143 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.101
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1144 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.102
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1145 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.103
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop
