Repository Alfresco/alfresco-process-infrastructure-deployment, pull requests merged in 2023-03, with the labels that each got.

#1045 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.77
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1046 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.3
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1047 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.4
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1050 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.6
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1051 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.13
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1053 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.14
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1054 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.15
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1055 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.16
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1057 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.17
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1059 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.19
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1060 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.20
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1061 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.21
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1062 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.22
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1063 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.24
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1064 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.25
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1065 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.27
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1066 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.28
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1052 AAE-12934 use the APA Docker image admin app
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved

#1069 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.1-alpha.1
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, 7.9.x

#1070 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.1-alpha.2
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, 7.9.x

#1068 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.31
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1072 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.33
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1073 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.34
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1075 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.35
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1076 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.36
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1077 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.1-alpha.3
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, 7.9.x

#1078 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.37
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1079 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.10.0-alpha.20
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1080 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.38
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1083 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.10.0-alpha.23
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1084 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.40
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1082 AAE-12946 Rename process analytics configuration host values to url
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: partially-approved, breaking-change

#1085 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.44
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1086 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.10.0-alpha.29
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1087 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.45
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1088 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.46
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1089 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.47
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1090 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.48
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1092 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.10.0-alpha.33
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1094 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.51
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop
