Repository Alfresco/alfresco-process-infrastructure-deployment, pull requests merged in 2023-01, with the labels that each got.

#941 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.8.0-alpha.14
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#942 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.29
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#943 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.30
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#944 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.31
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#923 [AAE-11890] Set content repository vars to Modeling Service
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: partially-approved

#946 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.32
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#948 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.33
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#949 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.34
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#950 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.8.0-alpha.17
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#951 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.35
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#952 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.8.0-alpha.18
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#953 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.36
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#954 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.37
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#955 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.39
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#956 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.40
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#957 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.41
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#958 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.42
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#960 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.43
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#961 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.44
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#962 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.45
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#963 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.46
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#964 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.47
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#965 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.8.0-alpha.25
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#966 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.48
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#967 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.49
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#968 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.50
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#969 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.51
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#971 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.53
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#972 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.54
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#973 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.55
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#974 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.8.0-alpha.56
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#977 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.2
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#978 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.3
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#979 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.4
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#980 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.9.0-alpha.6
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#981 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.5
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#982 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.6
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#983 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.8
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#985 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.9
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#986 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.10
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#987 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.14
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#989 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.9.0-alpha.16
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#990 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.16
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#991 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.17
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop
