Repository Alfresco/alfresco-process-infrastructure-deployment, pull requests merged in 2023-05, with the labels that each got.

#1146 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.104
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1148 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.106
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1149 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.107
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1150 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.10.0-alpha.108
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1154 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.2
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1155 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.3
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1158 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.6
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1159 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.8
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1161 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.11.0-alpha.9
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1163 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.10
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1164 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.11
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1166 chore(deps): upgrade Activiti/activiti-cloud-common-chart to version 7.11.0-alpha.1
  helm/alfresco-process-infrastructure/Chart.yaml
  helm/alfresco-process-infrastructure/README.md
Labels: updatebot, develop

#1167 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.11.0-alpha.10
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1168 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.13
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1171 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.16
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1173 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.18
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1174 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.19
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1175 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.20
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1176 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.11.0-alpha.19
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1177 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.21
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1178 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.22
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1151 AAE-13058 AAE-13059 modeling and deployment service configurations
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: enhancement, PR: unreviewed, PR: partially-approved

#1179 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.28
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1180 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.29
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1181 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.30
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1182 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.31
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1183 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.32
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1184 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.11.0-alpha.34
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1185 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.33
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1186 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.11.0-alpha.35
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1187 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.34
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1188 chore(deps): upgrade Alfresco/alfresco-identity-adapter-service to version 7.11.0-alpha.23
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1189 chore(deps): upgrade Alfresco/alfresco-identity-adapter-service to version 7.11.0-alpha.24
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1190 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.36
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1192 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.38
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1193 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.39
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1194 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.40
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1195 chore(deps): upgrade Alfresco/alfresco-identity-adapter-service to version 7.11.0-alpha.27
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1196 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.41
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1197 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.43
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1198 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.44
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1199 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.11.0-alpha.42
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1200 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.45
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1201 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.46
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1202 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.47
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1203 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.48
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1204 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.11.0-alpha.45
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1205 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.49
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1206 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.50
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1207 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.51
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1208 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.11.0-alpha.47
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1209 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.52
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1210 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.55
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1211 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.56
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1212 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.57
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1213 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.58
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1214 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.59
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1217 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.61
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1219 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.62
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1220 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.64
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1222 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.65
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1223 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.66
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1224 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.67
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1225 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.0-alpha.69
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop
