Repository Alfresco/alfresco-process-infrastructure-deployment, pull requests merged in 2023-02, with the labels that each got.

#992 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.9.0-alpha.18
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#993 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.18
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#994 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.19
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#995 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.20
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#996 chore(deps): upgrade Alfresco/alfresco-identity-adapter-service to version 7.9.0-alpha.13
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#998 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.34
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#999 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.35
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1000 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.36
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1001 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.37
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1002 chore(deps): upgrade Alfresco/alfresco-identity-adapter-service to version 7.9.0-alpha.17
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1003 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.39
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1004 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.41
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1006 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.43
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1007 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.44
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1008 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.45
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1010 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.9.0-alpha.37
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1011 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.46
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1012 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.47
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1013 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.9.0-alpha.40
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1014 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.48
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1016 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.49
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1017 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.50
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1018 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.51
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1019 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.52
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1020 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.54
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1021 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.55
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1022 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.58
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1023 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.59
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1024 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.9.0-alpha.50
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1025 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.60
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1028 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.63
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1029 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.64
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1030 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.65
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1031 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.66
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1032 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.67
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1033 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.9.0-alpha.56
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1034 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.68
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1035 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.70
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1036 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.72
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1037 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.73
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop

#1039 AAE-11710 Add defaults for redirect URIs in deployment service values
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved

#1043 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.75
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: reviewed-approved, updatebot, develop

#1042 AAE-11710 Remove defaults at chart level and add support for terraform setup
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: PR: reviewed-approved

#1044 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.9.0-alpha.76
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: PR: unreviewed, updatebot, develop
