Repository Alfresco/alfresco-process-infrastructure-deployment, pull requests merged in 2023-09, with the labels that each got.

#1430 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.12.0-alpha.190
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1431 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.12.0-alpha.193
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1429 AAE-15820 Configure Datadog Java Tracing to work with our existing Datadog Agent
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  values-datadog-metrics.yaml
  values-datadog.yaml
Labels: enhancement

#1434 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.12.0-alpha.194
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1436 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.12.0-alpha.199
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1437 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.12.0-alpha.200
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1438 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.12.0-alpha.144
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1439 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.12.0-alpha.201
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1440 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.12.0-alpha.202
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1442 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.12.0-alpha.204
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1444 AAE-16301 Add Datadog configuration support to AAE Infrastructure services Helm deployment
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/templates/_helpers.tpl
  helm/alfresco-process-infrastructure/values.yaml
  values-datadog-metrics.yaml
  values-datadog.yaml
Labels: enhancement

#1443 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.12.0-alpha.207
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1447 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.12.0-alpha.213
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1448 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.12.0-alpha.214
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1449 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.12.0-alpha.215
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1450 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.12.0-alpha.216
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1451 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.12.0-alpha.217
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1452 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.12.0-alpha.218
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1453 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.12.0-alpha.219
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1454 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.12.0-alpha.220
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1458 chore(deps): upgrade Activiti/activiti-cloud-common-chart to version 7.12.0-alpha.2
  helm/alfresco-process-infrastructure/Chart.yaml
  helm/alfresco-process-infrastructure/README.md
Labels: updatebot, develop

#1459 chore(deps): upgrade Activiti/activiti-cloud-common-chart to version 7.12.0-alpha.3
  helm/alfresco-process-infrastructure/Chart.yaml
  helm/alfresco-process-infrastructure/README.md
Labels: updatebot, develop

#1460 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.12.0-alpha.223
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1461 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.12.0-alpha.224
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1462 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.12.0-alpha.160
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1463 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.12.0-alpha.225
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1465 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.12.0-alpha.226
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1466 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.12.0-alpha.227
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1467 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.12.0-alpha.228
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1468 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.12.0-alpha.233
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1470 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.12.0-alpha.234
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1471 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.12.0-alpha.235
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1472 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.12.0-alpha.236
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1473 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.12.0-alpha.237
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1474 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.12.0-alpha.238
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1475 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.12.0-alpha.239
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1476 chore(deps): upgrade Alfresco/alfresco-modeling-service to version 7.12.0-alpha.164
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1478 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.12.0-alpha.242
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1479 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.12.0-alpha.243
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1481 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.11.2-alpha.1
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, 7.11.x

#1482 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.13.0-alpha.1
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1483 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.13.0-alpha.2
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1484 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.13.0-alpha.3
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop

#1485 chore(deps): upgrade Alfresco/alfresco-deployment-service to version 7.13.0-alpha.4
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop
