Repository Alfresco/alfresco-process-infrastructure-deployment, pull requests merged in 2024-07, with the labels that each got.

#2245 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.18.0-alpha.118
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2243 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.15.3-alpha.1
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, be-propagation, 7.15.x

#2246 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.18.0-alpha.121
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2247 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.18.0-alpha.122
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2248 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.18.0-alpha.123
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2250 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.18.0-alpha.124
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2253 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.1
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2254 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.2
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2255 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.5
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2256 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.7
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2257 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.8
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2258 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.9
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2259 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.10
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2260 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.11
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2261 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.12
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2262 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.13
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2263 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.14
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2264 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.15
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2265 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.16
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2266 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.17
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2268 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.18
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2269 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.19
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2270 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.21
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2272 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.22
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2273 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.24
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2274 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.25
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2275 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.26
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2276 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.27
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2277 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.28
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2278 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.29
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2279 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.30
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2281 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.31
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2283 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.33
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2284 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.34
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2285 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.35
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2286 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.36
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2287 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.37
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2288 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.38
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2289 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.39
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2290 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.40
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2291 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.41
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2293 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.42
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2294 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.43
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2295 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.44
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2297 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.45
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2298 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.46
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2299 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.47
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2300 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.48
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2301 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.49
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2302 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.50
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2292 AAE-24037 Adjust studio account level apps memory requests
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
Labels: enhancement

#2303 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.51
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2304 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.55
  helm/alfresco-process-infrastructure/Chart.yaml
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2306 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.56
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2307 chore(deps): upgrade Alfresco/alfresco-identity-adapter-service to version 7.19.0-alpha.44
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation

#2308 chore(deps): upgrade Alfresco/hxp-studio-services to version 7.19.0-alpha.59
  helm/alfresco-process-infrastructure/README.md
  helm/alfresco-process-infrastructure/values.yaml
  pom.xml
Labels: updatebot, develop, be-propagation
